---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/601ccdcf6dd9f2001621e1e2/webhook/forestry'
sections:
- type: document
  path: config.yaml
  label: Site Configuration
  templates:
  - config
- type: document
  path: data/author.json
  label: Author
  templates:
  - author
- type: directory
  path: content
  label: Pages
  create: all
  match: '**/*'
  new_doc_ext: md
  templates:
  - advanced
  - page
  - post
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
version: 0.80.0
